### PR TITLE
OS Independent

### PR DESCRIPTION
**Pull request by jinankjain**
I have changed db.sqlite3 because now the new system does not require path to be ended by \ so I have removed that initial entry of testuser1 and made a new entry.

@ybdesire  Now we should also remove test011 because it is no longer required and that would be the only case that fails while running test

### CODE REVIEW

**Comment by ybdesire** [comment]
Great work! Thanks Jinank!!
I will test the code change at Windows environment and try to merge it ASAP.
My only concern is the compatibility of the code change. Actually my test cases are not perfect for all situations at Win & Linux. Would you provide more test cases for your solution?
Such as "create a file at path with multiple folders /home/xxx/yyy/zzz/ and c:\home\xxx\yyy\zzz" ... ...

**Comment by jinankjain** [comment]
Test Cases which I am planning to add are:

1) It will ensure that whether parent folder is created or not otherwise give an error message.
2) Creating nested folder like testuser1/book , testuser1/book/jinank, testuser1/book/jinank/ybdesire 
3) Check the output op=list is coming properly or not

And now we need to remove test011 as it is no longer required that path should end with \ as we have made path independent of OS

**Comment by ybdesire** [comment]
Good ideas. Thanks. And I suggest we don't touch src/api/SyncFileAPI/db.sqlite3 for PR unless you have better reason. Since some data in db file is necessary for current test cases.

**Comment by jinankjain** [comment]
We have to change db.sqilte3 because of this change I have made it as like
original, I have added testuser1. We no longer need path to end with \
thats why I have changed db.sqlite3
ᐧ

**Comment by ybdesire** [comment]
Got that. I will test it. Give me more time~~

**Comment by jinankjain** [comment]
@ybdesire Cool everything was working fine

**Comment by ybdesire** [comment]
Thanks Jinank for the PR. And waiting for the test cases update :)

**Pull request merged**
